language: node_js
node_js:
  - lts/*

script:
  - echo "Fix the tests at some point please!"

before_deploy: npm run build

deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    branch: develop
    repo: beer-garden/angular-schema-form-addons
  email: beerbuildbot
  api_key:
    secure: lt53Tq2y9eaTMsL1DdXzcX0zxbJHuHy3z0lKexLwBQyUiy+1Kl3w7QrOI1HZJZnXJN+dM+0gymvVx3clNy9WDJDcupcoakAdD6vjGxvbxmJ2tgiZtvbdwQas726kRzAu0bOBLno3h3SV/ZuLilcqSYzJ25Wrh3cHpuA5yW3Dz25Uh6/plGdd/OpywDyW9gwPIWxZUPhE3J8qGdjYhuBtmJn2bkmfKAPha6MSZPT2l9d6eMjfSf65SX94/DqAohHi0H29SPD/U+VaA8gYh1il0PWNfauwX5G+Sg59TT8668LnieLycFKWZI6i/Uk61PZNLyzxqLrf1fcY/TdjFQnYRIHdmFzlzh1W8HTPe2xAC/aQ34zzlPA/NVY2rcIL45tXPWii9yBZtBYy/4JGDooyKqaPLdmi0V9EU7DQlVkmM95kBQPiw8NFJoxGfJhVYsaGQ/XxCjlnrAVmlhbelxXEA/7ASZ/rtpSt5/HHfO/WB8I6MAVUAyH9LP0wyPp5oDfEawcrjbh2SQgIbMx02elozW/mVD354jtw6PbBwBsvsZ/UwNvQg7ha+l0y/sOH5p0BukEAbrQuH+g7nVD6LbpWB8uyMUMxsvWj+11oE99gVBYqFgadki6vxcLxMnAYmXIkC2XE6TEU5Kt4HyESmBTh6xPXSApjjpBRPnpGrhoXZp0=
