language: node_js
node_js:
  - lts/*

script:
  - echo "Fix the tests at some point please!"

deploy:
  provider: npm
  email: buildbot@beer-garden.io
  api_key:
    secure: CTeuQ0u8v+qhkzM243tXioVpDnMGEXNQ4ObcN/idZ+P7uZr3QBUnE5VqS7gJODxa/Te7DxgD57iOeYZ5vWLVfmOddu8TDVyxPvujMkQ0Fdzfd3+cNImj0v09jfOhGlg1b6D5JX0LQZGbntNlzEVHbbQdtVGO0ZUlN3q8KRtlwhvBTNTAsS4XVbToUp0p7+0cafHWksYrALioBLegD9bz5pjopw6PFYh2koTfc7q5b5V0ytnlHlrjbc/Mp2Fg3b90KTOmQU2xLNnKotIrkxCJndCx983Imo9e1thT6e+8TEDPT7MrA58iz7+Jip5tvLfXGFZtwWVPB9hK2EGRVNBcLv00HjjkgzxzIOyiOgEFuR3SnfYFiP3P87lZ4X1+UvSLUxvbBRbhGBmGiIz7i4nzGzoK61NqdDKPRkfy3Fc2ANHgL7nCUFzoRVB2wyRM4pRBRmWc9IxheB+bl5YzVDtK2C7YRGiPNlQnWien/QBfGaKscyL/JXEweItfC/WPoM2xO2ZYnlGvJzTuNOKTMS65Gr8N5vBtHKQWNoYJXONvEGSQtQJAJj224mvp1u8HiipiC1x8NpamX3sGHrnHyJ+m5YAoAFD/5P1HdWY8cFj+M0rEFOWuReZXtvykoCZ43iqWojpW3x8IZje5JPUpJ+GUXfXmDMz7+gZYCC8kmlEO0Ac=
  on:
    tags: true
    repo: beer-garden/angular-schema-form-addons
    branch: develop
